oname: Build
description: 'Install macOS specific dependencies'

inputs:
  shell:
    required: false
    default: bash

runs:
  using: 'composite'
  steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3

    - name: Add custom Homebrew repos
      shell:  ${{inputs.shell}}
      run: brew tap pothosware/homebrew-pothos && brew update

    # Reinstall step needed to fix the problem with @loader_path
    - name: (Re) Install libsndfile
      shell: ${{inputs.shell}}
      run: brew reinstall libsndfile

    - name: Install Volk
      shell: ${{inputs.shell}}
      run: brew install volk

    - name: Install JSON-C
      shell: ${{inputs.shell}}
      run: brew install json-c

    - name: Install FFTW
      shell: ${{inputs.shell}}
      run: brew install fftw

    - name: Install SoapySDR
      shell: ${{inputs.shell}}
      run: brew install soapysdr

    - name: Install libxml2
      shell: ${{inputs.shell}}
      run: brew install libxml2

    - name: Install portaudio
      shell: ${{inputs.shell}}
      run: brew install portaudio

    - name: Install SoapySDR modules
      shell: ${{inputs.shell}}
      run: |
        brew install soapyrtlsdr soapyhackrf soapybladerf soapyairspy soapyredpitaya soapyiris limesuite soapyplutosdr
        brew install --head soapyuhd

    - name: Install SDRPlay
      shell: ${{inputs.shell}}
      run: |
        wget https://www.sdrplay.com/software/SDRplayAPI-macos-installer-universal-3.14.0.pkg
        sudo installer -pkg SDRplayAPI-macos-installer-universal-3.14.0.pkg -target /
        # SoapySDRPlay3 from source
        git clone https://github.com/pothosware/SoapySDRPlay3
        cd SoapySDRPlay3
        cmake -DCMAKE_BUILD_TYPE=Release -B build .
        cmake --build build
        cd build
        sudo make install
        cd ../..
